name = "Polymania"
author = "Patbox"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d4d7a395c777679dd223c056f3ef7761c5bde5b21b800a7fe0eec0c291a49b8"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
