name = "Polymania"
author = "Patbox"
version = "<MODPACKVERSION>"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4994dcbe04f582c94c30fdcc49b557bfb263ea1fbfafca49b86aa017df5afeed"

[versions]
fabric = "0.16.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1", "1.21"]
datapack-folder = "resources/common/required"
